{
 "title": "Finances",
 "time": { "from": "2023-02-21T09:00:24.713Z", "to": "2024-10-21T08:04:23.615Z" },
 "templating": {
  "list": [
   { "name": "table", "query": "epargne, table2" }
  ]
 },
 "panels": [
  {
   "title": "Epargne",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(solde) \r\nFROM epargne \r\nWHERE date = (SELECT MAX(date) FROM epargne)"
    }
   ]
  },
  {
   "title": "PEA",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sum(solde) \r\nFROM pea \r\nWHERE type_compte = 'Valorisation totale' and date = (SELECT MAX(date) FROM pea)"
    }
   ]
  },
  {
   "title": "Epargne",
   "type": "timeseries",
   "description": "Evolution du solde d'épargne",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT date, SUM(solde) as Livrets FROM ${table} WHERE type_compte NOT IN ( 'PEA' ) GROUP BY date"
    }
   ]
  },
  {
   "title": "PEA",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT date, type_compte, solde FROM pea ORDER BY date "
    }
   ]
  },
  {
   "title": "Nombre de valeur",
   "type": "timeseries",
   "description": "Evolution du solde d'épargne",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "rawSql": "SELECT date, count(*) FROM ${table} where type_compte <> 'PEA' group BY date;"
    },
    {
     "rawSql": "SELECT date, count(*) as ajout FROM ${table} where type_compte = 'ajout' group BY date;"
    }
   ]
  }
 ]
}