{
 "title": "Finances",
 "time": { "from": "2019-07-01T00:00:00.000Z", "to": "2025-01-01T01:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "table", "query": "epargne, table2" }
  ]
 },
 "panels": [
  {
   "title": "Epargne",
   "type": "timeseries",
   "description": "Evolution du solde d'épargne",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT date, SUM(solde) as Livrets FROM ${table} WHERE type_compte NOT IN ( 'PEA' ) GROUP BY date"
    }
   ]
  },
  {
   "title": "PEA",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "rawSql": "SELECT date, type_compte, solde FROM pea ORDER BY date "
    }
   ]
  },
  {
   "title": "Nombre de valeur",
   "type": "timeseries",
   "description": "Evolution du solde d'épargne",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT date, count(*) FROM ${table} where type_compte <> 'PEA' group BY date;"
    },
    {
     "rawSql": "SELECT date, count(*) as ajout FROM ${table} where type_compte = 'ajout' group BY date;"
    }
   ]
  }
 ]
}